#' Returns the location of the most recent peptides and modified conditions file (v2)
#'
#' @return path for the last folder, peptides file and conditions file
#' @param data pep_data generated by preppetide, it is a list where 4th element contains information about conditions
#' @export
#' @import dplyr
#' @importFrom magrittr %>%
#' @examples findlastpepfile()
findlastpepfile_v2 <- function(data = pep_data) {

  # which is the last folder
  mypath <- getwd()
  last_folder <- paste0(mypath, "/", data[[4]][1], "_vs_", data[[4]][2])
  # peptides and the labels file from that folder
  peptides               <- paste0(last_folder, "/peptidesformsempire.txt")
  labels                 <- paste0(last_folder, "/conditions_dual.txt")

  # save locations in the list to read it during msempire analysis
  locations_last <- list()
  locations_last[[1]] <- paste0(last_folder, "/peptidesformsempire.txt")
  locations_last[[2]] <- paste0(last_folder, "/conditions_dual.txt")
  locations_last[[3]] <- last_folder

  # return path
  return(locations_last)
}
