#' Nested functions of the pepquantify package
#' @description this wraps many functions of this package. For the description see the description of each function (preppeptide, peptimpute and findlastpepfile)
#'
#' @param data list of two containing peptide and protein group data generated by the read functions of the pepquant package
#' @param n_element_peptide peptide data is the nth element (usually not necessary to change)
#' @param condition1 name of the first condition that should be compared (note that order matters for the fold-change direction)
#' @param condition2 name of the second condition that should be compared (note that order matters for the fold-change direction)
#' @param n_condition_1 minimum number of the valid values in the first condition (this value should be at least two, but default pepquant value is three)
#' @param n_condition_2 minimum number of the valid values in the second condition (this value should be at least two, but default pepquant value is three)
#' @param min_pep minimum number of peptides for each protein
#' @param downshift see the perseus documentation "Replace missing values from normal distribution"
#' @param width     see the perseus documentation "Replace missing values from normal distribution"
#' @param n_ko_like minimum number of peptides that should have missing and valid value pattern (all valid in one condition, less than 2 in the second or otherwise by user defined criteria) default 2
#' @param fraction_valid between 0-1. 1 means that imputed peptides are taken into account if they are present in all samples of one of the conditions, 0.5 means if they are present in the half of the samples of one of the conditions. default 1
#' @param second_condition maximum acceptable number of valid values in other condition when fraction valid is met in the other, default 1
#' @param seed set seed as values for imputation are derived randomly, seed makes sure the reproducibility. default 1234
#' @param imputation if true imputation will be performed if set to false no imputation will be performed
#' @return locations_last
#' @export
#'
#' @examples pepquantify_funs(data, condition1, condition2)
pepquantify_funs <- function(data, imputation = FALSE, n_element_peptide = 1, condition1, condition2,
                             n_condition_1 = 3, n_condition_2 = 3, min_pep = 2,
                             downshift = 1.8, width = 0.3, n_ko_like = 2, fraction_valid = 1,
                             second_condition = 1, seed = 1234) {

# prepere peptide (writes MS-EmpiRe ready files, they will be overwritten if impute is set to true)
pep_data <-  pepquantify::preppeptide(data, n_element_peptide = n_element_peptide,
                                      condition1 = condition1, condition2 = condition2,
                                      n_condition_1 = n_condition_1, n_condition_2 = n_condition_2,
                                      min_pep = min_pep)
# should imputation be performed
  if (imputation == TRUE) {
pepquantify::peptimpute(pep_data, downshift = downshift, width = width,
                        n_ko_like = n_ko_like,
                        fraction_valid = fraction_valid,
                        second_condition = second_condition, seed = seed)
  }


# this will find where the necessary files are to pass this information to MS-EmpiRe
locations_last <- pepquantify::findlastpepfile_v2(data = pep_data)


# return the last path
return(locations_last)


}
