#' Tidy the results generated by the MS-EmpiRe
#'
#' @param fc_threshold minimum fold change for the protein to be considered differentially abundant (in natural scale) default 1.5
#' @param data  path returned from the findlastpepfile (or pepquantify_funs (recommended))
#' @param data2 this is the output of the pepquantify package read functions
#' @export
#' @import utils dplyr stringr tidyr
#' @importFrom magrittr %>%
#' @examples resultstidy(fc_threshold = 1.5, data)
resultstidy <- function(fc_threshold = 1.5, data, data2) {


  # read the conditions file (this is to define the fold-change direction)
  conditions <- read.delim(data[[2]], sep = "\t", header = T)



  # which conditions are there
  c_1 <- conditions %>% dplyr::select(.data$Condition) %>% dplyr::filter(stringr::str_detect(.data$Condition, "A_")) %>%
    dplyr::filter(dplyr::row_number()==1)  %>%
    as.character() %>%
    stringr::str_remove("A_")
  c_2 <- conditions %>% dplyr::select(.data$Condition) %>%
    dplyr::filter(stringr::str_detect(.data$Condition, "B_")) %>%
    dplyr::filter(dplyr::row_number() == 1) %>%
    as.character() %>%
    stringr::str_remove("B_")



  # read msempire results
  msempire_results <- read.delim(paste0(data[[3]], "/msempire_results_raw.txt"), sep = "\t", header = T)



  # msempire data clean-up
  msempire_results <- msempire_results %>%
    dplyr::select(
      accession          = .data$prot.id,
      l2fc               = .data$log2FC,
      p_value            = .data$p.val,
      adj_p_value        = .data$p.adj) %>%
    dplyr::mutate(l2fc = -1*.data$l2fc) %>%
    dplyr::mutate(
      significant = dplyr::case_when(
        .data$adj_p_value < 0.05 & abs(.data$l2fc) > log2(fc_threshold) ~ "+"),
      diff_abundant = dplyr::case_when(
        .data$adj_p_value < 0.05 & .data$l2fc >  log2(fc_threshold) ~ paste0("upregulated_in_",    c_1),
        .data$adj_p_value < 0.05 & .data$l2fc < -log2(fc_threshold) ~ paste0("downregulated_in_", c_1),
        TRUE ~ "n.s."
      )) %>%
    dplyr::arrange(.data$significant, dplyr::desc(.data$l2fc))



  # adds numbers of total and imputed peptides
  peptnumbers <- read.delim(data[[1]], sep = "\t", header = T) %>%
   dplyr::select(-starts_with("Intensity.")) %>%
   dplyr::mutate(id = stringr::str_remove(.data$unique_id, "\\.[0-9]*$")) %>%
   dplyr::select(-.data$unique_id) %>%
   dplyr::rename(accession = .data$id)


  # number of peptides for which the data was imputed (check first if they are present)
  if (ncol(peptnumbers) == 3) {

    n_missingpeptide <- peptnumbers %>%
      dplyr::select(.data$accession, .data$n_ko) %>%
      tidyr::drop_na() %>%
      dplyr::rename(n_imputed = .data$n_ko) %>%
      dplyr::distinct()



  # add information about imputed peptides to the results
    msempire_results <- msempire_results %>%
      dplyr::left_join(n_missingpeptide) %>%
      dplyr::mutate(n_imputed = tidyr::replace_na(.data$n_imputed, 0))

  }



  # number of peptides with a valid values
  n_validpeptide <- peptnumbers %>%
    dplyr::select(.data$accession, .data$n_pep) %>%
    dplyr::rename(n_pep_total = .data$n_pep) %>%
    dplyr::distinct()




  # add previous information
  msempire_results <- msempire_results %>%
    dplyr::left_join(n_validpeptide) %>%
    dplyr::mutate(significant = tidyr::replace_na(.data$significant, "n.s."))



  # gets extra information from the protein groups files (different for dda and dia)
  if (data2[[3]] == "DDA") {

      msempire_results$fastaheader <- data2[[2]]$Fasta.headers[match(msempire_results$accession, data2[[2]]$Protein.IDs)]

    }



  # save the tidy results
  write.table(msempire_results, paste0(data[[3]], "/msempire_results_tidy.txt"), sep = "\t", row.names = F)



  # save the results that can be used to plot the volcano plot
  msempire_results_volcano <- msempire_results %>%
    dplyr::select(1:6) %>%
    dplyr::mutate_all(~dplyr::na_if(., 0))


  #replace P values having value of 1 with with the highest value which is not 1 (this is to properly logarithmize)
  # logarithmize p-value column for plotting as y axis on Volcano
  msempire_results_volcano$log10p=-log10(msempire_results_volcano$p_value)
  msempire_results_volcano$log10p[is.na(msempire_results_volcano$log10p)] <- max(msempire_results_volcano$log10p, na.rm = T)
  msempire_results_volcano$log10p[msempire_results_volcano$log10p == 0] <- NA
  msempire_results_volcano$log10p[is.na(msempire_results_volcano$log10p)] <-  min(msempire_results_volcano$log10p, na.rm = T)
  write.table(msempire_results_volcano, paste0(data[[3]], "/msempire_results_tidy_volcano.txt"), sep = "\t", row.names = F)




  # print the information
cat("three files were saved in the working directory:
    1 - msempire_results_raw:     this is the raw results of MS-EmpiRe
    2 - msempire_results_tidy:    this is the results that has been cleaned-up and can be used in suppl tables
    3 - msempire_results_volcano: some columns was adjusted to make it suitable for the volcano plot")
}



